// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaazufmixewbgpbzvlij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhYXp1Zm1peGV3YmdwYnp2bGlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NTk0OTksImV4cCI6MjA3NDAzNTQ5OX0.cGQTpm9cQlex3fcOXRQB3MWEqcxUjbQN9zUQZ-4vLxs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});